
clustername: kube
okd_version: 4.6
okd_nodeport: 30036
traefik_version: v2.3

nfs_server: "192.168.0.10"
nfs_path_scratch: "scratch"
nfs_path: "/{{ nfs_path_scratch }}/kube-"
nfs_storage:
  - { "name": "pv1g-01", "size": 1}
  - { "name": "pv1g-02", "size": 1}
  - { "name": "pv1g-03", "size": 1}
  - { "name": "pv10g-01", "size": 10}
  - { "name": "pv10g-02", "size": 10}
  - { "name": "pv10g-03", "size": 10}
  - { "name": "pv10g-04", "size": 10}
  - { "name": "pv10g-05", "size": 10}

local_storage:
  - { "name": "local1g-01", "size": 1}
  - { "name": "local1g-02", "size": 1}
  - { "name": "local1g-03", "size": 1}
  - { "name": "local10g-01", "size": 10}
  - { "name": "local10g-02", "size": 10}
