---
- name: "[SSH-Key] Manage SSH key for Foreman"
  hosts: foremanservers
  # Foreman uses ssh authentication to communicate with KVM
  # This play manages the .ssh directory for foreman and foreman-proxy:
  # install the ansible ssh key, scan network for kvm hosts and add their keys to known_hosts
  #
  pre_tasks:
  # Setup SSH for Foreman Proxy
  - name: "[SSH-Key] Install the SSH key to Foreman proxy"
    include_role:
      name: config_ssh_key
      tasks_from: ssh_copy_key.yml
    vars:
      key_private: "{{ ansible_private_key }}"
      key_public: "{{ ansible_public_key }}"
      key_path: "/usr/share/foreman-proxy/.ssh"
      private_key_name: id_rsa
      ssh_user_name: foreman-proxy
      ssh_user_create_home: no
      ssh_touch_known_hosts: "/usr/share/foreman-proxy/.ssh/known_hosts"
      ssh_touch_authorized_keys: "/usr/share/foreman-proxy/.ssh/authorized_keys"
      key_owner: foreman-proxy
      key_group: foreman-proxy
      key_permission: "0600"
  - name: "[SSH-Key] Perform Keyscan for foreman proxy"
    include_role:
      name: config_ssh_key
      tasks_from: ssh_keyscan.yml
    vars:
      ssh_known_hosts_path: /usr/share/foreman-proxy/.ssh/known_hosts
      ssh_remote_host: "{{ kvm_host }}"
      ssh_user_name: foreman-proxy
    with_items:
      - "{{ groups['kvm_hypervisors'] }}"
    loop_control:
      loop_var: kvm_host

  # Setup SSH for Foreman
  - name: "[SSH-Key] Install the SSH key to Foreman"
    include_role:
      name: config_ssh_key
      tasks_from: ssh_copy_key.yml
    vars:
      key_path: "/usr/share/foreman/.ssh"
      private_key_name: id_rsa
      key_private: "{{ ansible_private_key }}"
      key_public: "{{ ansible_public_key }}"
      ssh_user_name: foreman
      ssh_user_create_home: no
      key_owner: foreman
      key_group: foreman
      key_permission: "0600"
  - name: "[SSH-Key] Perform Keyscan for foreman"
    include_role:
      name: config_ssh_key
      tasks_from: ssh_keyscan.yml
    vars:
      ssh_known_hosts_path: /usr/share/foreman/.ssh/known_hosts
      ssh_remote_host: "{{ kvm_host }}"
      ssh_user_name: foreman
    with_items:
      - "{{ groups['kvm_hypervisors'] }}"
    loop_control:
      loop_var: kvm_host

  roles:
    - common
    - service_foreman_server
