---
- hosts: kube_nodes
  roles:
    - common

- hosts: kube_seed
  tasks:
  - include_role:
      name: service_kube
      tasks_from: bootstrap.yaml
- hosts: kube_masters
  tasks:
  - include_role:
      name: service_kube
      tasks_from: masters.yaml
- hosts: kube_nodes
  tasks:
  - include_role:
      name: service_kube
      tasks_from: workers.yaml
- hosts: k8s-node6
  tasks:
  - include_role:
      name: service_kube
      tasks_from: access-nodes.yaml
- hosts: kube_seed
  tasks:
  - include_role:
      name: service_kube
      tasks_from: config.yaml
