---
- hosts: kvm_hypervisors
  roles:
    - config_redhat
    - common
    - { role: config_vdo, vdo_name: "{{ kvm_vdo_name }}", dev_name: "{{ kvm_vdo_dev }}", mountpoint: '/var/lib/libvirt/images', vdo_scale: 10, vdo_lv_size: "{{ kvm_vdo_size }}" }
    - service_dnsmasq
    - { role: config_nfs, server: "{{ nfs_server }}", share_name: nas, src: "{{ nfs_path_data }}"}
    - service_terraform
    - service_kvm_hypervisor
