---
#- name: "[VMs] Configure hosts in VM group"
#  hosts: vms
#  roles:
#    - common
#    - config_ipa_client

- import_playbook: free-ipa.yml
- import_playbook: kvm.yml
- import_playbook: satellite.yml

- name: "[Logging] Configure central logging"
  import_playbook: logging.yml

#- include: rasp-m3.yml
