---

- name: restart_network
  systemd:
    name: network.service
    state: restarted

- name: restart_libvirt
  systemd:
    name: network.service
    state: restarted

- name: systemd_reload
  systemd:
    daemon_reload: yes
