---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: external-access
  namespace: my-argocd-operator
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist: []
  orphanedResources:
    warn: false

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-access-rules
  namespace: my-argocd-operator
  labels:
    argo-project: external-access
spec:
  destination:
    namespace: {{ ns }}
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://github.com/ThomasBuchinger/access-rules
    targetRevision: 'HEAD'
    path: "access"
  project: default
  syncPolicy:
    automated:
      selfHeal: true
