---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devel
  namespace: my-argocd-operator
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: false

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-registry
  namespace: my-argocd-operator
spec:
  destination:
    namespace: {{ ns }}
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://kubernetes-charts.storage.googleapis.com
    targetRevision: '1.9.4'
    chart: docker-registry
    helm:
      parameters: []
  project: devel
  syncPolicy:
    automated: {}