---
- name: "[Configure] Create KVM Link"
  command: "python ./hammer.py compute-resource create --name {{ kvm_name }} --provider libvirt --url qemu+ssh://{{ kvm_host }}/system --display-type VNC --set-console-password no"
  args:
    chdir: "{{ work_dir }}/service_foreman_server"
  register: cmd
  failed_when: cmd.rc >= 2
  changed_when: cmd.rc == 1
