---
- name: "[Configure] Create VCTR Link"
  command: "python ./hammer.py compute-resource create --name {{ compute_resource }} --datacenter {{ compute_datacenter }} --provider vmware --server {{ vctr_host }} --user {{ vctr_user }} --password {{ vctr_password }} --url invalid"
  args:
    chdir: "{{ work_dir }}/service_foreman_server"
  register: cmd
  failed_when: cmd.rc >= 2
  changed_when: cmd.rc == 1

- name: "[Configure] Create domain: {{ ipa_domain }}"
  command: "python ./hammer.py domain create --name {{ ipa_domain }}"
  args:
    chdir: "{{ work_dir }}/service_foreman_server"
  register: cmd
  failed_when: cmd.rc >= 2
- name: "[Configure] Create Network {{ compute_network }}"
  command: "python ./hammer.py subnet create --name {{ default_net_name }} --boot-mode=Static --dns-primary {{ ipa_ip }} --domains {{ ipa_domain }} --mask '255.255.255.0' --network {{ default_net_id }} --gateway={{ default_net_gateway }} --tftp-id AUTO_PROXY_{{ ansible_fqdn }} --dns-id AUTO_PROXY_{{ ansible_fqdn }} --dhcp-id AUTO_PROXY_{{ ansible_fqdn }}"
  args:
    chdir: "{{ work_dir }}/service_foreman_server"
  register: cmd
  failed_when: cmd.rc >= 2
  changed_when: cmd.rc == 1

- name: "[Configure] Copy Configuration templates into place"
  copy:
    src: "{{ item }}"
    dest: "{{ work_dir }}/service_foreman_server/"
    force: yes
  with_fileglob:
    - "*.cfg"

- name: "[Configure] Create partition tables"
  command: "python ./hammer.py partition-table create --name {{ item|basename |regex_replace('ks-(.*).cfg$', 'BUC-\\1')|quote }} --file ./{{ item|basename }}  --os-family Redhat"
  args:
    chdir: "{{ work_dir }}/service_foreman_server"
  register: cmd
  failed_when: cmd.rc >= 2
  changed_when: cmd.rc == 1
  with_fileglob:
    - "*.cfg"

- name: "[Configure] Create OS: CentOS"
  command: "python ./hammer.py os create --name 'CentOS' --architectures 'x86_64' --description 'CentOS' --family 'Redhat' --major 7 --media 'CentOS mirror' --password-hash SHA512"
  args:
    chdir: "{{ work_dir }}/service_foreman_server"
  register: os_cmd
  failed_when: os_cmd.rc >= 2
- name: "[Configure] Configure OS: CentOS"
  command: "python ./post-config-os.py --os 'CentOS' --provision 'Kickstart default' --pxe 'Kickstart default PXELinux' --partition BUC-partition-tiny BUC-partition-var BUC-partition-opt"
  args:
    chdir: "{{ work_dir }}/service_foreman_server"
  when: os_cmd.changed
  register: cmd
  failed_when: cmd.rc >= 2
  

- name: "[Configure] Create Host Group: {{ default_host_group }}"
  command: "python ./hammer.py hostgroup create --name {{ default_host_group }} --architecture x86_64 --domain {{ ipa_domain }} --environment production --operatingsystem 'CentOS' --medium 'CentOS mirror' --partition-table 'BUC-partition-var' --puppet-ca-proxy {{ ansible_fqdn }} --puppet-proxy {{ ansible_fqdn }} --root-pass 'changeme' --subnet '{{ default_net_name }}'"
  args:
    chdir: "{{ work_dir }}/service_foreman_server"
  register: cmd
  failed_when: cmd.rc >= 2
  changed_when: cmd.rc == 1
