---
- name: "[Configure] Create domain: {{ ipa_domain }}"
  command: "python ./hammer.py domain create --name {{ ipa_domain }}"
  args:
    chdir: "{{ work_dir }}/service_foreman_server"
  register: cmd
  failed_when: cmd.rc >= 2
- name: "[Configure] Create Network {{ compute_network }}"
  command: "python ./hammer.py subnet create --name {{ default_net_name }} --boot-mode=Static --dns-primary {{ ipa_ip }} --dns-secondary {{ default_net_gateway }} --domains {{ ipa_domain }} --mask '255.255.255.0' --network {{ default_net_id }} --gateway={{ default_net_gateway }} --tftp-id AUTO_PROXY_{{ ansible_fqdn }} --dns-id AUTO_PROXY_{{ ansible_fqdn }} --dhcp-id AUTO_PROXY_{{ ansible_fqdn }}"
  args:
    chdir: "{{ work_dir }}/service_foreman_server"
  register: cmd
  failed_when: cmd.rc >= 2
  changed_when: cmd.rc == 1



- name: "[Configure] Copy Configuration templates into place"
  copy:
    src: "{{ item }}"
    dest: "{{ work_dir }}/service_foreman_server/"
    force: yes
  with_fileglob:
    - "*.cfg"

- name: "[Configure] Create partition tables"
  command: "python ./hammer.py partition-table create --name {{ item|basename |regex_replace('ks-(.*).cfg$', 'BUC-\\1')|quote }} --file ./{{ item|basename }}  --os-family Redhat"
  args:
    chdir: "{{ work_dir }}/service_foreman_server"
  register: cmd
  failed_when: cmd.rc >= 2
  changed_when: cmd.rc == 1
  with_fileglob:
    - "*.cfg"


- name: "[Configure] Create OS: CentOS 7"
  command: "python ./hammer.py os create --name 'Centos7' --architectures 'x86_64' --description 'Centos7' --family 'Redhat' --major 7 --media 'CentOS mirror' --password-hash SHA512"
  args:
    chdir: "{{ work_dir }}/service_foreman_server"
  register: os_cmd
  failed_when: os_cmd.rc >= 2
- name: "[Configure] Configure OS: CentOS 7"
  command: "python ./post-config-os.py --os 'Centos7' --provision 'Kickstart default' --pxe 'Kickstart default PXELinux' --partition BUC-partition-tiny BUC-partition-var BUC-partition-opt"
  args:
    chdir: "{{ work_dir }}/service_foreman_server"
  when: os_cmd.changed
  register: cmd
  failed_when: cmd.rc >= 2


- name: "[Configure] Create Install Media: CentOS 8"
  command: "python ./hammer.py medium create --name 'Centos8' --os-family 'Redhat' --path 'http://mirror.centos.org/centos/$major/BaseOS/$arch/os/'"
  args:
    chdir: "{{ work_dir }}/service_foreman_server"
  register: os_cmd
  failed_when: os_cmd.rc >= 2
- name: "[Configure] Create OS: CentOS 8"
  command: "python ./hammer.py os create --name 'Centos8' --architectures 'x86_64' --description 'Centos8' --family 'Redhat' --major 8 --media 'Centos8' --password-hash SHA512"
  args:
    chdir: "{{ work_dir }}/service_foreman_server"
  register: os_cmd
  failed_when: os_cmd.rc >= 2
- name: "[Configure] Configure OS: CentOS 8"
  command: "python ./post-config-os.py --os 'Centos8' --provision 'Kickstart default' --pxe 'Kickstart default PXELinux' --partition BUC-partition-tiny BUC-partition-var BUC-partition-opt"
  args:
    chdir: "{{ work_dir }}/service_foreman_server"
  when: os_cmd.changed
  register: cmd
  failed_when: cmd.rc >= 2


- name: "[Configure] Create Environment: production"
  command: "python ./hammer.py environment create --name production"
  args:
    chdir: "{{ work_dir }}/service_foreman_server"
  register: cmd
  failed_when: cmd.rc >= 2
  changed_when: cmd.rc == 1

- name: "[Configure] Create Host Group: {{ default_host_group }}"
  command:
    argv:
      - python
      - ./hammer.py
      - hostgroup
      - create 
      - --name
      - "{{ default_host_group }}"
      - --architecture
      - x86_64
      - --domain
      - "{{ ipa_domain }}"
      - --environment
      - production
      - --operatingsystem
      - Centos8
      - --medium
      - Centos8
      - --compute-resource
      - "{{ foreman_default_compute }}"
      - --pxe-loader
      - PXELinux UEFI
      - --partition-table
      - BUC-partition-tiny
      - --root-pass
      - changeme
      - --subnet
      - "{{ default_net_name }}"
  args:
    chdir: "{{ work_dir }}/service_foreman_server"
  register: cmd
  failed_when: cmd.rc >= 2
  changed_when: cmd.rc == 1
