---
- name: "[Setup] Run Proxy Plugin installation"
  command: >
    foreman-installer --detailed-exitcodes  --no-colors
    --enable-foreman-proxy  
      --foreman-proxy-register-in-foreman=true
      --foreman-proxy-registered-name={{ ansible_fqdn }}

    --enable-foreman-proxy-plugin-ansible
      
    --enable-foreman-proxy-plugin-openscap
      --foreman-proxy-plugin-openscap-contentdir="/var/lib/foreman-proxy/openscap/content"
      --foreman-proxy-plugin-openscap-failed-dir="/var/lib/foreman-proxy/openscap/failed"
      --foreman-proxy-plugin-openscap-openscap-send-log-file="/var/log/foreman-proxy/openscap-send.log"
      --foreman-proxy-plugin-openscap-reportsdir="/var/lib/foreman-proxy/openscap/reports"
      --foreman-proxy-plugin-openscap-spooldir="/var/spool/foreman-proxy/openscap"

    --enable-foreman-proxy-plugin-remote-execution-ssh
      --foreman-proxy-plugin-remote-execution-ssh-generate-keys=false
      --foreman-proxy-plugin-remote-execution-ssh-install-key=true
      --foreman-proxy-plugin-remote-execution-ssh-local-working-dir="/var/tmp"
      --foreman-proxy-plugin-remote-execution-ssh-ssh-identity-dir="/usr/share/foreman-proxy/.ssh"
      --foreman-proxy-plugin-remote-execution-ssh-ssh-identity-file=id_rsa
      --foreman-proxy-plugin-remote-execution-ssh-ssh-keygen="/usr/bin/ssh-keygen"
 
  register: cmd
  changed_when: cmd.rc == 2
  failed_when: cmd.rc !=0 and cmd.rc !=2

