---
- name: "Prepare Host / Set FQDN"
  hostname:
    name: "{{ ansible_hostname }}.{{ ipa_domain }}"

- name: "Prepare Host / Set /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ ansible_default_ipv4.address }}"
    line: "{{ ansible_default_ipv4.address }}    {{ ansible_fqdn }} {{ ansible_hostname }}"
    backup: no

- name: "Prepare Host / Install EPEL 7 Repo for SCL & python"
  dnf:
    name:
    - "@python38:3.8/common"
    - "@ruby:2.5/common"
    - epel-release
    - http://yum.puppet.com/puppet6-release-el-8.noarch.rpm
    - "https://yum.theforeman.org/releases/{{ foreman_version }}/el8/x86_64/foreman-release.rpm"
    state: present
    validate_certs: no
  when: ansible_distribution_major_version == "8"
#- name: Prepare Host / Configure Python
#  alternatives:
#    name: python
#    path: /usr/bin/python3
#  when: ansible_distribution_major_version == "8"
  
- name: "Prepare Host / Install EPEL"
  yum:
    name:
      - epel-release
      - http://yum.puppet.com/puppet6-release-el-7.noarch.rpm
      - https://yum.theforeman.org/releases/latest/el7/x86_64/foreman-release.rpm
      - foreman-release-scl
    state: present
    validate_certs: no
  when: ansible_distribution_major_version == "7"

#- name: "Prepare Host / Installing release repositories"
#  yum:
#    name:
#      - http://yum.puppet.com/puppet6-release-el-7.noarch.rpm
#      - https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
#      - "https://yum.theforeman.org/releases/{{ foreman_version }}/el7/x86_64/foreman-release.rpm"
#    state: present
#    validate_certs: no
- name: "Prepare Host / Install foreman-installer"
  yum:
    name:
      - foreman-installer
    state: present
- name: "Prepare Host / Create Foreman Directory"
  file:
    name: /etc/foreman-installer/scenarios.d/
    state: directory

- name: "Prepare Host / Create work directory"
  file:
    name: "{{ work_dir }}/service_foreman_server"
    state: directory
- name: "Prepare Host / Copy helper scripts to target"
  copy:
    src: "{{ item }}"
    dest: "{{ work_dir }}/service_foreman_server/{{ item}}"
    mode: 755
  with_items: 
  - "hammer.py"
  - "post-config-os.py"

