---
# The installation does not work with ansible 2.7
# remove any previous installed ansible versions, and let the script handle the installation
# https://github.com/gshipley/installcentos/issues/109
- name: "[FIX] Remove any existing ansible package"
  yum:
    name: "ansible"
    state: absent
