

- name: Config / Create work_dir
  file:
    path: "{{ work_dir }}/app_kube"
    state: directory

- import_tasks: config_okd-console.yaml

- import_tasks: config_ingress.yaml

- import_tasks: config_external-ingress.yaml

- import_tasks: config_storage_longhorn.yaml

