- name: "[Install] Install ansible, git and EPEL"
  yum:
    name:
      - ansible
      - git
      - epel-release
      - python-dns
    state: present


#- name: "[VMware] Install python-pip (from epel)"
#  yum:
#    name:
#      python-pip
#    state: present
#- name: "[VMware] Install python bindings"
#  pip:
#    name: 
#    - pysphere
#    - pyvmomi
#    state: present 

- name: "[Install] Create Directory"
  file:
    name: "{{ ansible_path }}/cred"
    state: directory
- name: "[Install] Install public key for ansible use"
  copy:
    src: id_rsa.pub
    dest: "{{ ansible_path}}/cred/{{ ansible_private_key_name }}.pub"
    mode: 0600
- name: "[Install] Install private key for ansible use"
  copy:
    src: id_rsa
    dest: "{{ ansible_path }}/cred/{{ ansible_private_key_name }}"
    mode: 0600
#- name: "[Install] Pull repostitory"
#  git:
#    repo: "{{ ansible_git_url }}"
#    dest: "{{ ansible_path }}/repo"
#    key_file: "{{ ansible_path }}/cred/{{ ansible_private_key_name }}"
#    accept_hostkey: yes

- name: "[Configure] Configure Ansible install "
  lineinfile:
    dest: /etc/ansible/ansible.cfg
    regexp: "roles_path"
    line: "roles_path={{ ansible_path }}/repo/roles"
