---
- name: "[Password-Policy] Create permission: Set Password Expire"
  ipa_permission:
    name: "Set Password Expire"
    right: all
    attributes: 
      - 'krbpasswordexpiration'
      - 'krbticketflags'
    object_type: user
    state: "present"
    ipa_host: "{{ ansible_fqdn }}"
    ipa_pass: "{{ ipa_admin_password }}"
    validate_certs: no

- name: "[Password-Policy] Grant 'Set Password Expire' permission to 'Password Policy Administrators' privilige"
  ipa_privilege:
    name: "Password Policy Administrator"
    permissions:
      - "Set Password Expire"
    mode: "add"
    state: "present"
    ipa_host: "{{ ansible_fqdn }}"
    ipa_pass: "{{ ipa_admin_password }}"
    validate_certs: no

- name: "[Password-Policy] Create Role 'Ansible Automation' and assign privilege 'Password Policy Administrators'"
  ipa_role:
    name: "Ansible Automation"
    group:
      - admins
    privilege:
      - "Password Policy Administrator"
    state: "present"
    ipa_host: "{{ ansible_fqdn }}"
    ipa_pass: "{{ ipa_admin_password }}"
    validate_certs: no
