---
- name: "[User] WORKAROUND: Delete User: {{ item.name }}"
  ipa_user: 
    name: "{{ item.name }}"
    state: absent
    validate_certs: false
    ipa_host: "{{ ansible_fqdn }}"
    ipa_user: "{{ ipa_admin_user }}"
    ipa_pass: "{{ ipa_admin_password }}"

- name: "[User] Configure User: {{ item.name }}"
  ipa_user:
    name: "{{ item.name }}"
    displayname: "{{ item.fullname }}"
    givenname: "{{ item.firstname }}"
    password: "{{ item.password }}"
    sn: "{{ item.lastname }}"
    telephonenumber: "{{ item.phone }}"
    state: present
    mail: "{{ item.mail }}"
    title: "{{ item.job }}"
    loginshell: "{{ item.shell }}"
    validate_certs: false
#    This options will be available in Ansible 2.5 (and apparently FreeIPA >4.5)
#    krbpasswordexpiration: "20380101235959"
    ipa_host: "{{ ansible_fqdn }}"
    ipa_user: "{{ ipa_admin_user }}"
    ipa_pass: "{{ ipa_admin_password }}"

- name: "[User] Set Password expire Date"
  shell: "echo '{{ ipa_admin_password }}' | kinit {{ ipa_admin_user }}; ipa user-mod {{ item.name }} --setattr='krbpasswordexpiration=20380101235959Z' "
