
# === Operators ====================================================
- name: Kube APP / Operators / Deploy Operator Lifecyle Manager 
  command: "kubectl apply -f {{ item }}"
  loop:
    - https://raw.githubusercontent.com/operator-framework/operator-lifecycle-manager/{{ olm_version }}/deploy/upstream/quickstart/crds.yaml
    - https://raw.githubusercontent.com/operator-framework/operator-lifecycle-manager/{{ olm_version }}/deploy/upstream/quickstart/olm.yaml
- name: Kube APP / Operators / Install Operators
  command: "kubectl apply -f {{ item }}"
  loop:
    - https://operatorhub.io/install/argocd-operator.yaml
    - https://operatorhub.io/install/tektoncd-operator.yaml
    - https://operatorhub.io/install/kiali.yaml # Banzai Cloud Operator: Istio uses the native operator
    - https://operatorhub.io/install/strimzi-kafka-operator.yaml
    - https://operatorhub.io/install/postgres-operator.yaml
    # - https://operatorhub.io/install/couchdb-operator.yaml
    # - https://raw.githubusercontent.com/rook/rook/release-1.4/cluster/examples/kubernetes/ceph/common.yaml # Rolebindings for Rook
    # - https://operatorhub.io/install/rook-ceph.yaml
    # - https://operatorhub.io/install/kubevirt.yaml
    # - https://operatorhub.io/install/elastic-cloud-eck.yaml
    # - https://operatorhub.io/install/project-quay.yaml # Does no work,, due to wrong CRD

 
- name: Kube APP / Operators / Manually create ns for Jaeger operator
  import_tasks: create_ns.yaml
  vars:
    ns: monitor
- name: Kube APP / Operators / Manually install Jaeger Operator
  command: "kubectl apply -n monitor -f {{ item }}"
  loop:
    - https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing.io_jaegers_crd.yaml
    - https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/service_account.yaml
    - https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/role.yaml
    - https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/role_binding.yaml
    - https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/operator.yaml
    - https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/cluster_role.yaml
    - https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/cluster_role_binding.yaml


#- name: Kube APP / Operators / Manually install Istio Operator
#  command: "kubectl apply -k {{ item }}"
#  loop:
#    - https://github.com/istio/istio/operator/deploy/

- name: Kube APP / Operators / Wait for CRD created
  command: "kubectl -n my-argocd-operator wait --for condition=established --timeout=60s crd/{{ item }}"
  retries: 15
  delay: 60
  register: result
  until: result.rc == 0
  loop:
    - argocds.argoproj.io
    # - cephclusters.ceph.rook.io  
