---
- name: "[Keyscan] Lookup hostname in inventory"
  set_fact:
    ssh_host: "{{ hostvars[ssh_remote_host]['ansible_host'] }}"
  when: hostvars[ssh_remote_host]['ansible_host'] is defined


- name: "[Keyscan] Scan available keys"
  command: "ssh-keyscan -t rsa,ecdsa,ed25519 {{ ssh_host }}"
  register: keys
  changed_when: false
  when: ssh_host is defined

#- name: "[SSH] Remove any existing SSH keys from known_hosts"
#  lineinfile:
#    regexp: "{{ ssh_host }}"
#    state: absent
#    path: "{{ ssh_known_hosts_path }}"
#  when: ssh_host is defined

- name: "[Keyscan] Create known_hosts file"
  file: 
    path: "{{ ssh_known_hosts_path }}"
    mode: 0644
    owner: "{{ ssh_user_name|default(omit) }}" 
    group: "{{ ssh_user_name|default(omit) }}"
    state: touch

- name: "[Keyscan] Add current SSH keys to known_hosts"
  lineinfile:
    regexp: "{{ ssh_item|regex_replace('^([^\\s]+) (ssh-[_\\-\\w]+)', '\\1 \\2')|regex_escape() }}"
    line: "{{ ssh_item }}"
    path: "{{ ssh_known_hosts_path }}"
    state: present
  with_items:
    - "{{ keys.stdout_lines| select('search','ssh-') | list }}"
  loop_control:
    loop_var: "ssh_item"
  when: ssh_host is defined

