
- fail:
    msg: "key_path needs to be sepcified"
  when: key_path is not defined

- import_tasks: create_ssh_user.yml
  when: ssh_user_name is defined

- name: "Copy SSH key / Create Directory"
  file:
    name: "{{ key_path }}/"
    state: directory
- name: "Copy SSH key / Copy public key"
  copy:
    content: "{{ key_public }}"
    dest: "{{ key_path}}/{{ private_key_name }}.pub"
    mode: "{{ key_permission|default(omit) }}"
    owner: "{{ key_owner|default(omit) }}"
    group: "{{ key_group|default(omit) }}"

- name: "Copy SSH key / Copy private key"
  copy:
    content: "{{ key_private }}"
    dest: "{{ key_path }}/{{ private_key_name }}"
    mode: "{{ key_permission|default(omit) }}"
    owner: "{{ key_owner|default(omit) }}"
    group: "{{ key_group|default(omit) }}"

