
- fail:
    msg: "key_path needs to be sepcified"
  when: key_path is not defined

- import_tasks: create_ssh_user.yml
  when: ssh_user_name is defined

- name: "[Install] Create Directory"
  file:
    name: "{{ key_path }}/"
    state: directory
- name: "[Install] Install public key for ansible use"
  copy:
    src: id_rsa.pub
    dest: "{{ key_path}}/{{ private_key_name }}.pub"
    mode: "{{ key_permission|default(omit) }}"
    owner: "{{ key_owner|default(omit) }}"
    group: "{{ key_group|default(omit) }}"

- name: "[Install] Install private key for ansible use"
  copy:
    src: id_rsa
    dest: "{{ key_path }}/{{ private_key_name }}"
    mode: "{{ key_permission|default(omit) }}"
    owner: "{{ key_owner|default(omit) }}"
    group: "{{ key_group|default(omit) }}"

