- name: "[RHEL] Install Redhat Packages"
  include: redhat.yml
  when: ansible_os_family|lower == 'redhat' and not(ansible_distribution|lower == 'fedora')
- name: "[Fedora] Install Fedora Packages"
  include: fedora.yml
  when: ansible_distribution|lower == 'fedora'

- name: "[Time] Setup Time Synchronisation"
  yum:
    name: "chrony"
    state: present
- name: "[Time] Starting Chronyd"
  service:
    name: "chronyd"
    state: started
    enabled: yes
#- include: network.yml

- name: "[SSH] disable reverse DNS lookups"
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'UseDNS no'
    regexp: '#?UseDNS '

- name: "[Cockpit] Install Cockpit"
  yum:
    name:
    - cockpit-docker
    - cockpit-selinux
    - cockpit-storaged
    - cockpit-bridge
    - cockpit-ws
    - cockpit
    - cockpit-pcp
    - cockpit-system
    - cockpit-dashboard
    - cockpit-packagekit
    state: present
- name: "[Cockpit] Configure Firewall"
  firewalld:
    service: cockpit
    immediate: true
    permanent: true
    state: enabled
- name: "[Cockpit] Enable Cockpit "
  systemd:
    name: cockpit.socket
    state: started
    enabled: true


#- name: "Install Debian Tasks"
#  include: debian.yml
#  when: ansible_os_family|lower == 'debian'
