---
- name: dnsmasq / Install Package
  yum:
    name: dnsmasq
    state: present

- name: dnsmasq / Enable Service
  systemd:
    name: dnsmasq.service
    state: started
    enabled: yes

- name: dnsmasq / Open firewall
  firewalld:
    port: 53/udp
    permanent: yes
    immediate: yes
    state: enabled

- name: dnsmasq / Copy configuration
  template:
    src: dnsmasq.conf.j2
    dest: "/etc/dnsmasq.d/config_by_ansible.conf"
  notify: restart_dnsmasq

- name: dnsmasq / Edit /etc/hosts
  lineinfile:
    line: "{{ item }}"
    dest: "/etc/hosts"
  loop: "{{ dnsmasq_etc_hosts }}"
  when: dnsmasq_etc_hosts is defined
  notify: restart_dnsmasq

