---
- name: "[RedHat] Register system to RHSM"
  redhat_subscription:
    state: present
    username: "{{ rhsm_user }}"
    password: "{{ rhsm_password }}"
    autosubscribe: true

- name: "[RedHat] Enable extras Repo"
  rhsm_repository:
    name: "{{ item }}"
    state: enabled
  with_items:
    - "rhel-{{ ansible_distribution_major_version }}-server-optional-rpms"
    - "rhel-{{ ansible_distribution_major_version }}-server-extras-rpms"
  when: ansible_distribution_major_version == '7'

- name: "[[RedHat] Enable additional Repos"
  rhsm_repository:
    name: 
      - rhel-8-for-x86_64-supplementary-rpms
    state: present
  when: ansible_distribution_major_version == '8'

- name: "[EPEL] Install EPEL Repository"
  yum: 
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version}}.noarch.rpm"
    state: present
  when: ansible_distribution_major_version == '7'
