---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: default-longhorn
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: keep-longhorn
provisioner: driver.longhorn.io
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""


---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  rules:
    - host: longhorn.{{ clustername }}.{{ ipa_domain }} 
      http:
        paths:
          - path: /
            backend:
              serviceName: longhorn-frontend
              servicePort: 80
