---

- name: "Storage / {{ pool.name }} / Create directory"
  file:
    path: "{{ pool.dir }}"
    state: directory

- name: "Storage / {{ pool.name }} / Define storage pool"
  virt_pool:
    name: "{{ pool.name }}"
    state: present
    xml: '{{ lookup("template", "storage_default.xml.j2") }}'
- name: "Storage / Start default storage"
  virt_pool:
    name: "{{ pool.name }}"
    state: active
- name: "Storage / Set autostart for default storage"
  virt_pool:
    name: "{{ pool.name }}"
    autostart: true 

