---
- name: "Install / Install Packages"
  yum:
    name:
      - qemu-kvm
      - libvirt
      - virt-install
      - libguestfs-tools 
    state: present
- name: "Install / RHEL 7 python bindings"
  yum:
    name:
      - libvirt-python
      - python-lxml
    state: present
  when: ansible_distribution_major_version == '7'
- name: "Install / RHEL 8 python bindings"
  yum:
    name:
      - python3-libvirt
      - python3-lxml 
    state: present
  when: ansible_distribution_major_version == '8'



- name: "Install / Enable Service"
  systemd:
    name: libvirtd
    enabled: yes
    state: started

- name: "Install / Configure KVM Kernel Params"
  template:
    src: kvm-kernel_params.conf
    dest: /etc/modprobe.d/kvm.conf

- import_tasks: network_bridge.yml
- import_tasks: storage_default.yml

- name: "Cockpit / Install cockpit plugin for libvirt"
  yum:
    name:
      - cockpit-machines
    state: present
