---
- name: "[Install] Install Packages"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - qemu-kvm
    - libvirt
    - libvirt-python
    - virt-install
    - libguestfs-tools 
    - python-lxml

- name: "[Install] Enable Service"
  systemd:
    name: libvirtd
    enabled: yes
    state: started

- name: "[Install] Configure KVM Kernel Params"
  template:
    src: kvm-kernel_params.conf
    dest: /etc/modprobe.d/kvm.conf

- import_tasks: network_bridge.yml
- import_tasks: storage_default.yml
- import_tasks: management_setup.yml

