---
- name: "[Install] Install Packages"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - qemu-kvm
    - libvirt
    - libvirt-python
    - virt-install
    - libguestfs-tools 
    - python-lxml

- name: "[Install] Enable Service"
  systemd:
    name: libvirtd
    enabled: yes
    state: started

- import_tasks: network_bridge.yml


