---
- name: "[Cockpit] Install cockpit plugin for libvirt"
  yum:
    name:
      - cockpit-machines
    state: present

# WebVirtMgr clone from git
#
#- name: "[WebVirtManager] Set app_path "
#  set_fact:
#    name: "kvm_webvirtmgr_path"
#    value: "{{ work_dir }}/service_kvm_hypervisor/webvirtmgr" 
- name: "[WebVirtManager] Install WebVirtManager RPM dependencies"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - git 
    - python-pip 
    - libvirt-python 
    - libxml2-python 
    - python-websockify
    - python-devel
    - gcc
    - numpy
- name: "[WebVirtManager] Clone GIT Repo"
  git:
    repo: git://github.com/retspen/webvirtmgr.git
    dest: "{{ webvirtmgr_path }}" 
    update: no

# WebVirtMgr Customization
#
- name: "[WebVirtManager Custom] Add Django PAM Auth Backend dependency"
  lineinfile:
    line: "django-pam"
    path: "{{ webvirtmgr_path }}/requirements.txt"
- name: "[WebVirtManager Custom] "
  template: 
    src: webvirtmgr_settings.py.j2
    dest: "{{ webvirtmgr_path }}/webvirtmgr/local/local_settings.py"


# WebVirtMgr Installation
#
- name: "[WebVirtManager] Install WebVirtManager PIP dependencies"
  pip:
    requirements: "{{ webvirtmgr_path }}/requirements.txt"
- name: "[WebVirtManager] Django syncdb"
  django_manage:
    command: "syncdb --noinput"
    app_path: "{{ webvirtmgr_path }}"
- name: "[WebVirtManager] Django collectstatic"
  django_manage:
    command: "collectstatic --noinput"
    app_path: "{{ webvirtmgr_path }}"


- name: "[WebVirtManager] Install systemd file"
  template:
    src: webvirtmgr_systemd.service.j2
    dest: "/usr/lib/systemd/system/webvirtmgr.service"
  notify: systemd_reload

- name: "[WebVirtManager] Start Service"
  systemd:
    name: webvirtmgr.service
    state: started
    enabled: yes

- name: "[WebVirtManager] Configure Firewall port"
  firewalld:
    port: 8000/tcp
    permanent: true
    immediate: true
    state: enabled
