---

- name: "Storage / Create directory for default storage"
  file:
    path: "{{ libvirt_default_storage_dir }}"
    state: directory

- name: "Storage / Define default storage"
  virt_pool:
    name: default
    state: present
    xml: '{{ lookup("template", "storage_default.xml.j2") }}'
- name: "Storage / Start default storage"
  virt_pool:
    name: default
    state: active
- name: "Storage / Set autostart for default storage"
  virt_pool:
    name: default
    autostart: true 

